# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import registro.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('mac', models.CharField(blank=True, max_length=17, null=True, unique=True, validators=[registro.models.validate_MAC])),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('zona', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('ip', models.GenericIPAddressField()),
                ('ip_int', models.BigIntegerField(default=0)),
            ],
        ),
    ]
