# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20170928_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
